### ISSUE TITLE
Suricata y Telegraf se conectan al socket, pero las alertas no aparecen en influxdb

### ISSUE THREAD

**Issue by agomez76** [gomezander/composer-suri-tele-infl-graf#1]
Para que suricata y telegraf se conecten al socket, he creado un volumen llamado shared en /var/run/ y lo he incluido en los servicios de suricata y telegraf del archivo de configuración de docker compose.
![image](https://user-images.githubusercontent.com/98752341/180433408-d338ed29-b78b-491f-8294-4e74a10a3656.png)
![image](https://user-images.githubusercontent.com/98752341/180433458-2d93d741-7e3b-4323-a300-d215c2c6f3c0.png)

También he comentado el perfil de telegraf, ya que al tener que iniciar muchas veces el docker compose se me hacía más cómodo hacerlo directamente con **docker compose up -d**. No inicio el servicio de grafana ya que lo que me interesa ahora mismo es que los logs de suricata lleguen a influx.

Una vez iniciado el contenedor, influx no da ningún error con el socket, y suricata da uno al principio pero luego consigue conectarse.
![image](https://user-images.githubusercontent.com/98752341/180434406-765ea630-840f-41da-9871-d829c941a97a.png)
![image](https://user-images.githubusercontent.com/98752341/180434578-72d6ec82-26ac-4419-85d6-e06808b27c9c.png)

Sin embargo, en influxdb no hay datos de suricata
![image](https://user-images.githubusercontent.com/98752341/180434934-f76f0097-df64-4c2c-ad36-6a772688c261.png)

Por lo que he leído, suricata no crea el socket de comunicación, sino que se conecta a uno y envía los datos. He probado a crear un socket y esucharlo desde el host(ubuntu) con **nc -lkU suricata-stats.sock** y sí que recibe los datos de suricata, pero no sé cómo comprobar si se están recibiendo los datos cuando telegraf crea y escucha el socket.

También he entrado en los contenedores de suricata y telegraf para comprobar el estado del socket.
Contenedor de Suricata:
![image](https://user-images.githubusercontent.com/98752341/180436474-879b1872-64a4-4868-bd19-0dda144dd2ec.png)

Podemos ver que el socket está y que el owner es systemd-coredump

Contenedor de Telegraf:
![image](https://user-images.githubusercontent.com/98752341/180436773-5178ed3f-e0b4-4839-9da8-d18def3b794e.png)

Podemos ver que el socket está y que el owner es telegraf. Además podemos ver que el userid y groupid del directorio son 998 y 996, los mismos que el usuario de suricata en el contenedor de suricata, por lo que ambos contenedores pueden acceder al directorio.
![image](https://user-images.githubusercontent.com/98752341/180437321-b5ce624b-27d2-4db3-a3eb-87d824096d81.png)

**Comment by sfl0r3nz05** [comment]
Hilos abiertos para intentar resolver el issue:

- [Influxdb](https://community.influxdata.com/t/access-to-suricata-metrics-on-influxdb/25864/15)
- [Stackoverflow](https://stackoverflow.com/questions/73107850/suricata-ids-telegraf-error-client-message-is-too-long-disconnect-him/73118964#73118964)
